name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
      - name: Run tests
        run: ./Check.sh
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
